apiVersion: apps/v1
kind: Deployment
metadata:
  name: cowsay-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cowsay
  template:
    metadata:
      labels:
        app: cowsay
    spec:
      containers:
      - name: cowsay
        image: gcr.io/us-central1-docker.pkg.dev/${{ secrets.GKE_PROJECT }}/container/cowsay
        ports:
        - containerPort: 4499