apiVersion: apps/v1
kind: Deployment
metadata:
  name: cowsay-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cowsay
  template:
    metadata:
      labels:
        app: cowsay
    spec:
      containers:
      - name: cowsay
        image: us-central1-docker.pkg.dev/parabolic-hook-412914/container/cowsay:test
        ports:
        - containerPort: 4499